name: yuque
description: yuque desktop.

environment:
  sdk: '>=2.2.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.6.0'

dependencies:
  flutter:
    sdk: flutter

  ## 工具
  cupertino_icons: ^0.1.0
  path: 1.6.2
  dio: 2.1.3
  rxdart: 0.22.0
  sqflite: 1.1.5
  shared_preferences: 0.5.2 # 简单 kv 持久化存储
  path_provider: 1.1.0
  uuid: 2.0.1
  
  ## 组件
  flutter_html: ^0.10.1+hotfix.1 # 展示 html
  flutter_webview_plugin: 0.3.5 # 显示网页
  flutter_markdown: 0.2.0

  flutter_spinkit: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: any
  json_annotation: ^2.3.0 # json 序列化
  json_serializable: ^2.3.0


  flutter_local_notifications: 0.7.1+1 # 通知

flutter:
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
  assets:
    - assets/yuque.sql